#!/usr/bin/node

let fs = require("fs");
let Phrase = require("gkatzuky-palindrome");

let save_file = fs.openSync("save_file.txt", "w")

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    console.log("palindrome detected:", line);
    fs.writeSync(save_file, `${line}\n`)
  }
});

// we have to close the file
fs.closeSync(save_file);
